import { Poppins  } from "next/font/google"
import "./globals.css";
import { Lora } from "next/font/google";

const fontSans = Poppins ({
  subsets: ["latin"],
  weight: ['100' ,'200' ,'300', '400', '500' ,'600' ,'700', '800' ,'900'],
  variable: "--font-sans", });



export const metadata = {
  title: "Dayanand Gawade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={fontSans.className}>{children}</body>
    </html>
  );
}
